# Generated by Django 4.2.6 on 2023-12-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0002_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("photo", models.ImageField(upload_to="")),
            ],
        ),
    ]
